{% set version = "3.6.0" %}

package:
  name: geos
  version: {{ version }}

source:
  url: https://github.com/libgeos/libgeos/archive/{{ version }}.tar.gz
  sha256: 71f7257bcfe59b349efe47128c81efcb9a99e6e7f5bd70b65b0be2246ede09b6
  patches:
    - xmltester.cpp.patch  # [win]
    - GEOSGeom_createCollection.cpp.patch  # [win]
    - GEOSSTRtreeTest.cpp.patch  # [win]

build:
  number: 1
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    # pretty poor backcompat.  SO name changes each release.
    #   https://abi-laboratory.pro/tracker/timeline/geos/
    - {{ pin_subpackage('geos', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - msinttypes  # [win and vc<14]
    - cmake  # [win]
    - automake  # [not win]
    - libtool  # [not win]

test:
  commands:
    - geos-config --version  # [not win]
    - conda inspect linkages -p $PREFIX geos  # [not win]
    - conda inspect objects -p $PREFIX geos  # [osx]

about:
  home: http://trac.osgeo.org/geos/
  license: LGPLv2.1
  license_file: COPYING
  summary: 'Geometry Engine - Open Source.'
  description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology
    Suite (JTS). As such, it aims to contain the complete functionality of
    JTS in C++.
  doc_url: http://trac.osgeo.org/geos/
  dev_url: https://github.com/libgeos/libgeos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
